name: Automated Tests

on: [push]

jobs:
  test-lowest-number:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Test 1 - Ten Numbers
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
        diff test1_output.txt test_data/test1_expected.txt

    - name: Run Test 2 - One Number
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
        diff test2_output.txt test_data/test2_expected.txt

    - name: Run Test 3 - Blank File
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
        diff test3_output.txt test_data/test3_expected.txt
